## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - 1.4
notifications:
  email: false
git:
  depth: 99999999
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Douglass")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Douglass")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
